version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminsecret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - social-net
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost:6379
      REDIS_PASSWORD: 
      REDIS_DB: 0
    networks:
      - social-net
    volumes:
      - redis_data:/data

networks:
  social-net:
    driver: bridge

volumes:
  db-data:
  redis_data:
